from fileOperations import find_all_functions, format_generated_documentation, insert_documentation
from documentationGenerator import makeRequest

prompt = "\n\ncan you generate a triple quote multiline python docstrings for this code?"

functions_to_document = find_all_functions('example-input/example-python-code.py')
documentation_to_insert = []

print(len(functions_to_document), "functions to document found")

for fn in functions_to_document:
    documentation = makeRequest(fn[0] +prompt)
    
    formatted_documentation = format_generated_documentation(documentation)

    documentation_to_insert.append((formatted_documentation, fn[1]))


print("documentation generated by ChatGPT API")

insert_documentation('example-input/example-python-code.py', documentation_to_insert)

print("documentation inserted")